---
# getting my dotfile configuration

- name: setting up my dotfiles
  git:
    repo: https://github.com/nesousx/dotfiles.git
    dest: ~/.dotiles

- file:
    src: ~/.dotiles/zshrc
    dest: ~/.zshrc
    state: link
